version: "3"

services:
  app:
    container_name: macaw
    build: ./docker-images/app
    volumes:
      - ./shared:/macaw/new
    # ports:
    #   - 4443:4443
    # environment:
    #   - NODE_ENV=development
    #   - PORT=4443
    #   - REDIS=redis://cache
    #   - DB=mongodb://mongo/searchx
    #   - DEFAULT_SEARCH_PROVIDER=BING
    networks:
      - app
    links:
      - mongo:mongo
  mongo:
    image: 'mongo:3.4.1'
    container_name: mongo
    ports:
      - '0.0.0.0:27017:27017'
    volumes:
      - 'mongo:/data/db'
    networks:
      - app








volumes:
  mongo:

networks:
  app:
