version: "3"

services:
  mongo:
    image: 'mongo:3.4.1'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
    networks:
      - app
  app:
    container_name: macaw
    build: ./docker-images/app
    volumes:
      - ./:/var/www/app
    # ports:
    #   - 4443:4443
    # environment:
    #   - NODE_ENV=development
    #   - PORT=4443
    #   - REDIS=redis://cache
    #   - DB=mongodb://mongo/searchx
    #   - DEFAULT_SEARCH_PROVIDER=BING
    # networks:
    #   - app







volumes:
  mongo:

networks:
  app:
